apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend        # selector must ONLY contain labels
  ports:               # ports must be at same level as selector
    - protocol: TCP
      port: 5000
      targetPort: 5000
